const AWSServices:any[] = 
[
    { serviceName:    'Amazon Web Services', abbre: 'AWS' },
    { serviceName:    'Amazon Elasticsearch Service', abbre: 'Amazon ES'},
    { serviceName:    'Amazon Machine Image', abbre: 'AMI'},
    { serviceName:    'Application Programming Interface', abbre: 'API'},
    { serviceName:    'Artificial Intelligence', abbre: 'AI'},
    { serviceName:    'Access Control List', abbre: 'ACL'},
    { serviceName:    'Amazon Resource Name', abbre: 'ARN'},
    { serviceName:    'Availability Zone', abbre: 'AZ'},
    { serviceName:    'Auto Scaling Group', abbre: 'ASG'},
    { serviceName:    'Advanced Encryption System', abbre: 'AES'},
    { serviceName:    'Active Directory Federation Service', abbre: 'ADFS'},
    { serviceName:    'Content Delivery Network', abbre: 'CDN'},
    { serviceName:    'Command Line Interface', abbre: 'CLI'},
    { serviceName:    'Classless Inter-Domain Routing', abbre: 'CIDR'},
    { serviceName:    'Cross Origin Resource Sharing', abbre: 'CORS'},
    { serviceName:    'Continous Integration/Continous Deployment', abbre: 'CI/CD'},
    { serviceName:    'Database Migration Service', abbre: 'DMS'},
    { serviceName:    'Domain Name System', abbre: 'DNS'},
    { serviceName:    'Distritubed Denial of Service', abbre: 'DDoS'},
    { serviceName:    'Denial of Service', abbre: 'DoS'},
    { serviceName:    'Desktop as-a-Service', abbre: 'DaaS'},
    { serviceName:    'Elastic Compute Cloud', abbre: 'EC2'},
    { serviceName:    'EC2 Container Service', abbre: 'ECS'},
    { serviceName:    'Elastic File System', abbre: 'EFS'},
    { serviceName:    'Elastic Block Store', abbre: 'EBS'},
    { serviceName:    'Elastic MapReduce', abbre: 'EMR'},
    { serviceName:    'Elastic Load Balancer', abbre: 'ELB'},
    { serviceName:    'Elastic Load Balancing', abbre: 'ELB'},
    { serviceName:    'Elastic IP', abbre: 'EIP'},
    { serviceName:    'Elastic Network Interface', abbre: 'ENI'},
    { serviceName:    'First In First Out', abbre: 'FIFO'},
    { serviceName:    'Function as-a-Service', abbre: 'FaaS'},
    { serviceName:    'High-Performance Compute', abbre: 'HPC'},
    { serviceName:    'Hardware Virtual Machine', abbre: 'HVM'},
    { serviceName:    'Hypertext Transfer Protocol', abbre: 'HTTP'},
    { serviceName:    'HTTP Secure', abbre: 'HTTPS'},
    { serviceName:    'Identity & Access Management', abbre: 'IAM'},
    { serviceName:    'Internet Of Things', abbre: 'iOT'},
    { serviceName:    'S3 Infrequent Access', abbre: 'S3 IA'},
    { serviceName:    'Internet Small Computer Storage Interface', abbre: 'iSCSI'},
    { serviceName:    'Input/Output Operation Per Second', abbre: 'IOPS'},
    { serviceName:    'Internet Gateway', abbre: 'IGW'},
    { serviceName:    'Internet Control Message Protocol', abbre: 'ICMP'},
    { serviceName:    'Internet Protocol', abbre: 'IP'},
    { serviceName:    'Internet Protocol Security', abbre: 'IPSec'},
    { serviceName:    'Infrastructure-as-a-Service', abbre: 'IaaS'},
    { serviceName:    'JavaScript Object Notation', abbre: 'JSON'},
    { serviceName:    'Key Management Service', abbre: 'KMS'},
    { serviceName:    'Load Balancer', abbre: 'LB'},
    { serviceName:    'Multi-Factor Authentication', abbre: 'MFA'},
    { serviceName:    'Microsoft Terminal Service Client', abbre: 'MSTSC'},
    { serviceName:    'Massive Parallel Processing', abbre: 'MPP'},
    { serviceName:    'Man in the Middle Attack', abbre: 'MITM'},
    { serviceName:    'Multi Protocol Label Switching', abbre: 'MPLS'},
    { serviceName:    'Network File System', abbre: 'NFS'},
    { serviceName:    'Name Server', abbre: 'NS'},
    { serviceName:    'Network Address Translation', abbre: 'NAT'},
    { serviceName:    'Online Transaction Processing', abbre: 'OLTP'},
    { serviceName:    'Online Analytics Processing', abbre: 'OLAP'},
    { serviceName:    'Payment Card Industry Data Security Standard', abbre: 'PCI DSS'},
    { serviceName:    'ParaVirtual', abbre: 'PV'},
    { serviceName:    'Platform as a Service', abbre: 'PaaS'},
    { serviceName:    'Relational Database Service', abbre: 'RDS'},
    { serviceName:    'Reduced Redundancy Storage', abbre: 'RRS'},
    { serviceName:    'Redundant Array of Independent Disk', abbre: 'RAID'},
    { serviceName:    'Random-access Memory', abbre: 'RAM'},
    { serviceName:    'Simple Storage Service', abbre: 'S3'},
    { serviceName:    'Server Migration Service', abbre: 'SMS'},
    { serviceName:    'Simple Workflow Service', abbre: 'SWF'},
    { serviceName:    'Simple Notification Service', abbre: 'SNS'},
    { serviceName:    'Simple Queue Service', abbre: 'SQS'},
    { serviceName:    'Simple Email Service', abbre: 'SES'},
    { serviceName:    'Service Level Agreement', abbre: 'SLA'},
    { serviceName:    'Secure Socket Layer', abbre: 'SSL'},
    { serviceName:    'Server Side Encryption', abbre: 'SSE'},
    { serviceName:    'Start of Authority', abbre: 'SOA'},
    { serviceName:    'Software Development Kit', abbre: 'SDK'},
    { serviceName:    'Secure Shell', abbre: 'SSH'},
    { serviceName:    'Simple Object Access Protocol', abbre: 'SOAP'},
    { serviceName:    'Cell content', abbre: 'CC'},
    { serviceName:    'Single Sign-On', abbre: 'SSO'},
    { serviceName:    'Security Assertion Markup Language', abbre: 'SAML'},
    { serviceName:    'Software-as-a-Service', abbre: 'SaaS'},
    { serviceName:    'Security Token Service', abbre: 'STS'},
    { serviceName:    'Time To Live', abbre: 'TTL'},
    { serviceName:    'Transport Layer Security', abbre: 'TLS'},
    { serviceName:    'Trusted Platform Module', abbre: 'TPM'},
    { serviceName:    'Technical Program Manager', abbre: 'TPM'},
    { serviceName:    'Transaction Per Second', abbre: 'TPS'},
    { serviceName:    'Transmission Control Protocol', abbre: 'TCP'},
    { serviceName:    'Virtual Private Cloud', abbre: 'VPC'},
    { serviceName:    'Virtual Machine', abbre: 'VM'},
    { serviceName:    'Virtual Tape Library', abbre: 'VTL'},
    { serviceName:    'Virtual Private Network', abbre: 'VPN'},
    { serviceName:    'Virtual Local Area Network', abbre: 'VLAN'},
    { serviceName:    'Virtual Desktop Infrastructure', abbre: 'VDI'},
    { serviceName:    'Virtual Private Gateway', abbre: 'VPG'},
    { serviceName:    'Web Application Firewall', abbre: 'WAF'}
];

export default AWSServices;